
import { Geist, Geist_Mono } from "next/font/google";

import { Playfair_Display, Inter } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-playfair",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
  <head>
    <link
      href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@300;400;500&display=swap"
      rel="stylesheet"
    />
  </head>

  <body className={`${playfair.variable} ${inter.variable} antialiased`}>
  {children}
</body>
</html>
  );
}
